name: 🚀 Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  publish:
    name: 🧱 Publish package to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v6

      - name: 🧰 Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.2.2 --activate
          yarn --version

      - name: 🧰 Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          scope: "@chillicream"
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: 🏷 Get the version from tag
        run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: 🔍 Install dependencies
        run: yarn install --immutable

      - name: 🧰 Install npm@11.9.0
        run: npm install -g npm@11.9.0

      - name: 🏗️ Build package
        run: yarn build

      - name: 🏷️ Set version
        run: npm version $GIT_TAG --no-git-tag-version

      - name: 📦 Create tarball
        run: npm pack

      - name: 🚀 Publish tarball to npm
        run: |
          TARBALL="chillicream-nitro-github-actions-${GIT_TAG}.tgz"

          npm publish "./${TARBALL}" --access public --tag "latest" --provenance
        shell: bash

      - name: 📤 Upload tarball as artifact
        uses: actions/upload-artifact@v7
        with:
          name: chillicream-nitro-github-actions-${{ env.GIT_TAG }}.tgz
          path: chillicream-nitro-github-actions-${{ env.GIT_TAG }}.tgz
